### ISSUE TITLE
Formats should be lowercase

### ISSUE THREAD

**Issue by loicteixeira** [gamejolt/doc-game-api#12]
[Formats](https://github.com/gamejolt/doc-game-api/blob/master/v1.x/formats/index.md) should be lowercase. If you pass a non-lowercase format, the API does not return anything.

_Based on my experience with the API v1.0, I don't know how v1.2 behave on that regard._

**Comment by loicteixeira** [comment]
While the documentation should be updated, it would be nice to actually return a fail state with a clear message like "Unknow format. It should be json or keypair or ..."
Or to convert the required format to lower case so it works anyway :)

**Comment by hworld** [comment]
Good call with that one! The docs are definitely misleading.

**Comment by indiegamehunt** [comment]
Updating docs
