### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by loicteixeira** [gamejolt/doc-game-api#14]
On the [index](https://github.com/gamejolt/doc-game-api/blob/master/v1.x/index.md), the link to batch should be `https://github.com/gamejolt/doc-game-api/blob/master/v1.x/batch/index.md`

On the [users index](https://github.com/gamejolt/doc-game-api/blob/master/v1.x/users/index.md), the link to fetch should be `https://github.com/gamejolt/doc-game-api/blob/master/v1.x/users/fetch.md`

On the [trophies index](https://github.com/gamejolt/doc-game-api/blob/master/v1.x/trophies/index.md), the link to fetch should be `https://github.com/gamejolt/doc-game-api/blob/master/v1.x/trophies/fetch.md`

On the [scores index](https://github.com/gamejolt/doc-game-api/blob/master/v1.x/scores/index.md), the link to fetch should be `https://github.com/gamejolt/doc-game-api/blob/master/v1.x/scores/fetch.md`

On the [get-time index](https://github.com/gamejolt/doc-game-api/blob/master/v1.x/get-time/index.md), the link to fetch should be `https://github.com/gamejolt/doc-game-api/blob/master/v1.x/get-time/fetch.md`

On the [data-store index](https://github.com/gamejolt/doc-game-api/blob/master/v1.x/data-storage/index.md), the link to fetch should be `https://github.com/gamejolt/doc-game-api/blob/master/v1.x/data-storage/fetch.md`

**Comment by indiegamehunt** [comment]
All updated

**Comment by indiegamehunt** [comment]
In forthcoming update
