### ISSUE TITLE
Cannot get rank! [SOLVED]

### ISSUE THREAD

**Issue by RalleYTN** [gamejolt/doc-game-api#22]
/scores/get-rank/ gives back the same response like /scores/.
It was supposed to give me a single number but instead I get a bunch of score objects.

[already solved!]

**Comment by pablomayobre** [comment]
I'm pretty sure GameJolt has forums, this is a repo for API development, not one but the API maintainers will see your question here, you should try to post this stuff in the forums. Plus this are not issues on the API but on your end anyway.
