### ISSUE TITLE
trophies api call returns malformed json

### ISSUE THREAD

**Issue by InfectedBytes** [gamejolt/doc-game-api#25]
The trophies call returns a string starting with the letter 's' and followed by the expected json.
A call to https://gamejolt.com/api/game/v1_1/trophies?... will result in:
```
s{
    "response":{
        "success":"true",
        "trophies":[
            {
                "id":"12345",
                "title":"Bronze Trophy",
                "description":"I'm a bronze trophy.",
                "difficulty":"Bronze",
                "image_url":"...",
                "achieved":"false"
            }
        ]
    }
}
```

**Comment by YLivay** [comment]
This is hillarious and tragic if it's indeed the case. How are you testing this? what's printing this out?

**Comment by YLivay** [comment]
Confirmed this, fixing, thanks for reporting man!

**Comment by InfectedBytes** [comment]
nice 😄 
and thanks for the quick reply!

**Comment by YLivay** [comment]
That sucked to find, but it should be fixed! Again, thanks for reporting, this was an embarrassing issue to have...

**Comment by InfectedBytes** [comment]
thanks man!
out of curiosity, how the hell did that happen? 😄

**Comment by YLivay** [comment]
ctrl+s without the ctrl, placed an s outside the php block. it was parsed as html to be outputted. object buffering made it ridiculously and uneedlessly difficult to find hahaha.

bah, soon the game api will be rewritten to elixir anyways
