### ISSUE TITLE
Batch POST misleading.

### ISSUE THREAD

**Issue by hworld** [gamejolt/doc-game-api#6]
"Because the constructed URL can become quite lengthy, the entire request is sent via POST data. If the URL is not too long, you can send it via GET request as well."

This sentence is confusing. I think if it was changed so it said, "the entire request could be sent view POST data" instead. Basically, since the URLs can become lengthy, they can be sent via POST data. However, you're free to also pass it as GET.

**Comment by indiegamehunt** [comment]
Edited.
